debug-event:
  runs-on: ubuntu-latest
  if: github.event_name == 'pull_request_target'
  steps:
    - name: Debug Event
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Action: ${{ github.event.action }}"
        echo "PR merged: ${{ github.event.pull_request.merged }}"
        echo "Base ref: ${{ github.event.pull_request.base.ref }}"
        echo "Head ref: ${{ github.event.pull_request.head.ref }}"
        echo "PR number: ${{ github.event.pull_request.number }}"
        echo "PR title: ${{ github.event.pull_request.title }}"

generate-changeset:
  permissions:
    contents: write
    pull-requests: write
  runs-on: ubuntu-latest
  # Remove the needs dependency or make it conditional
  needs: ${{ github.event_name == 'pull_request_target' && fromJSON('["debug-event"]') || fromJSON('[]') }}
  if: (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch' 